import next from 'eslint-config-next';

/** @type {import('eslint').Linter.Config[]} */
const config = [
  ...next,
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'out/**',
      'build/**',
      // static, self-contained marketing site (CDN-based, no build step)
      'landing/**',
      // generated by `supabase gen types typescript`
      'lib/supabase/database.types.ts'
    ]
  }
];

export default config;
