import type { WorkspaceConfig } from "./types";

export const dashboardWorkspaces: WorkspaceConfig[] = [
  {
    key: "capital",
    title: "Capital Desk",
    eyebrow: "Raise capital",
    description: "Investor pipeline, follow-ups, soft commitments, and capital-raise readiness.",
    href: "/dashboard/capital",
    primaryAction: { label: "Open LP pipeline", href: "/source/lp_pipeline" },
    characterId: "capital-connector",
    recommendation: "Triage investor follow-ups first, then move the warmest prospects into diligence-ready rooms.",
  },
  {
    key: "deals",
    title: "Deal Desk",
    eyebrow: "Source deals",
    description: "Acquisition targets, underwriting status, seller conversations, diligence, and LOI tracking.",
    href: "/dashboard/deals",
    primaryAction: { label: "Open deal pipeline", href: "/source/deal_pipeline" },
    characterId: "deal-sourcer",
    recommendation: "Advance screened targets with missing diligence before starting new outbound deal sourcing.",
  },
  {
    key: "fund-room",
    title: "Fund Room",
    eyebrow: "Manage fund",
    description: "Fund profile, LP materials, subscription workflow, compliance milestones, and reporting calendar.",
    href: "/dashboard/fund-room",
    primaryAction: { label: "Open data room", href: "/build/data_room" },
    characterId: "capital-raiser",
    recommendation: "Close the fund-room readiness gaps before expanding investor outreach volume.",
  },
  {
    key: "investor-relations",
    title: "Investor Relations",
    eyebrow: "Report to investors",
    description: "LP updates, reporting readiness, investor Q&A, portal activity, and communication follow-ups.",
    href: "/dashboard/investor-relations",
    primaryAction: { label: "Open reporting", href: "/execute/reporting" },
    characterId: "investor-relations",
    recommendation: "Prepare the next LP update and keep outbound communication behind explicit approval.",
  },
  {
    key: "automation",
    title: "Automation Lab",
    eyebrow: "Automate workflow",
    description: "Workflow triggers, document automations, routing rules, integration health, and approval gates.",
    href: "/dashboard/automation",
    primaryAction: { label: "Open automations", href: "/automations" },
    characterId: "automater",
    recommendation: "Automate repeatable weekly summaries, but keep irreversible actions approval-gated.",
  },
  {
    key: "marketing",
    title: "Marketing Engine",
    eyebrow: "Build authority",
    description: "SEO tasks, PR calendar, social proof, campaign analytics, and authority content.",
    href: "/dashboard/marketing",
    primaryAction: { label: "Open brand studio", href: "/build/brand" },
    characterId: "pr-director",
    recommendation: "Turn milestone proof into investor-safe authority content before launching more campaigns.",
  },
];
